services:
  claude_flow:
    build:
      context: .
      dockerfile: Dockerfile # Path to Dockerfile relative to the context (project root)
    container_name: claude_flow_server
    command: node ./cli.js start
    ports:
      - "${MAIN_SERVER_PORT:-3000}:3000"
      - "${MCP_SERVER_PORT:-3001}:3001"
    env_file:
      - ./docker/.env # Path to .env file relative to where docker-compose is run (project root)
    volumes:
      - ../:/app # Mount project root to /app
      - claude_flow_node_modules:/app/node_modules
    restart: unless-stopped

volumes:
  claude_flow_node_modules:

networks:
  default:
    name: claude_flow_network
